# Generated by Django 2.2.8 on 2020-01-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200109_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='123456', max_length=30),
            preserve_default=False,
        ),
    ]
